import pg from "pg";
import { createHash } from "crypto";
import * as dotenv from "dotenv";
dotenv.config();

const pool = new pg.Pool({ connectionString: process.env.DATABASE_URL });

function hash(s: string): string {
  return createHash("sha256").update(s).digest("hex");
}

type ST = "federal" | "provincial" | "municipal" | "foundation" | "private";

interface GrantSeed {
  title: string;
  description: string;
  sourceName: string;
  sourceUrl: string;
  sourceType: ST;
  category: string[];
  amountMin: number | null;
  amountMax: number | null;
  deadline: Date | null;
  eligibility: string;
  howToApply: string;
}

const grants: GrantSeed[] = [
  // ===== FEDERAL GRANTS =====
  {
    title: "Women's Program — Capacity-Building Stream",
    description: "Non-repayable multi-year funding for organizations to build capacity and advance gender equality. Supports projects addressing systemic barriers faced by women, particularly those experiencing intersecting forms of discrimination.",
    sourceName: "Women and Gender Equality Canada (WAGE)",
    sourceUrl: "https://women-gender-equality.canada.ca/en/funding/funding-programs/womens-program-capacity-building.html",
    sourceType: "federal",
    category: ["Women", "Employment"],
    amountMin: 200000, amountMax: 1500000,
    deadline: new Date("2026-10-15"),
    eligibility: "Canadian non-profit organizations, Indigenous organizations, and community-based groups working to advance gender equality. Must demonstrate organizational capacity to manage multi-year projects.",
    howToApply: "Submit expression of interest through WAGE online funding portal. Shortlisted applicants invited for full proposal.",
  },
  {
    title: "Gender-Based Violence Program — Sector Support",
    description: "Non-repayable grants for organizations working to address gender-based violence in Canada. Funds capacity building, knowledge mobilization, and promising practices in GBV prevention and response.",
    sourceName: "Women and Gender Equality Canada (WAGE)",
    sourceUrl: "https://women-gender-equality.canada.ca/en/gender-based-violence/funding.html",
    sourceType: "federal",
    category: ["GBV", "Women"],
    amountMin: 75000, amountMax: 750000,
    deadline: new Date("2026-08-30"),
    eligibility: "Non-profit organizations with demonstrated expertise in GBV prevention, response, and survivor support. Priority to Indigenous, racialized, and 2SLGBTQ+ serving organizations.",
    howToApply: "Two-stage process: LOI then full application. Apply via WAGE portal.",
  },
  {
    title: "Social Development Partnerships Program — Children and Families",
    description: "Non-repayable contributions to community projects that improve outcomes for children, families, and vulnerable populations. Focus on innovation, knowledge-sharing, and partnerships.",
    sourceName: "Employment and Social Development Canada (ESDC)",
    sourceUrl: "https://www.canada.ca/en/employment-social-development/services/funding/social-development-partnerships-children-families.html",
    sourceType: "federal",
    category: ["Youth", "Education"],
    amountMin: 100000, amountMax: 750000,
    deadline: new Date("2026-09-15"),
    eligibility: "Non-profit organizations, Indigenous organizations, educational institutions, and municipalities delivering programs for children and families facing social challenges.",
    howToApply: "Apply through ESDC Grants and Contributions Online Services (GCOS).",
  },
  {
    title: "Social Development Partnerships Program — Disability",
    description: "Non-repayable funding for projects that improve participation and inclusion of people with disabilities in Canadian society. Supports systemic change and innovation.",
    sourceName: "Employment and Social Development Canada (ESDC)",
    sourceUrl: "https://www.canada.ca/en/employment-social-development/services/funding/social-development-partnerships-disability.html",
    sourceType: "federal",
    category: ["Health", "Employment"],
    amountMin: 50000, amountMax: 400000,
    deadline: new Date("2026-11-30"),
    eligibility: "Non-profit organizations with a focus on disability inclusion. Organizations led by people with disabilities given priority.",
    howToApply: "Submit via GCOS portal during the open call period.",
  },
  {
    title: "New Horizons for Seniors Program — Community-Based",
    description: "Non-repayable grants up to $25,000 for community projects engaging seniors. Supports social inclusion, elder abuse prevention, and intergenerational programming.",
    sourceName: "Employment and Social Development Canada (ESDC)",
    sourceUrl: "https://www.canada.ca/en/employment-social-development/services/funding/new-horizons-seniors-community-based.html",
    sourceType: "federal",
    category: ["Health", "General"],
    amountMin: 5000, amountMax: 25000,
    deadline: new Date("2026-12-15"),
    eligibility: "Non-profit organizations, Indigenous groups, and municipalities engaging seniors. Streamlined application for small grants.",
    howToApply: "Apply through ESDC online services. Annual call for proposals.",
  },
  {
    title: "New Horizons for Seniors — Pan-Canadian",
    description: "Larger non-repayable grants for national projects supporting seniors' social participation. Multi-year funding available.",
    sourceName: "Employment and Social Development Canada (ESDC)",
    sourceUrl: "https://www.canada.ca/en/employment-social-development/services/funding/new-horizons-seniors-pan-canadian.html",
    sourceType: "federal",
    category: ["Health"],
    amountMin: 250000, amountMax: 5000000,
    deadline: new Date("2026-10-30"),
    eligibility: "Non-profit organizations with pan-Canadian reach and proven capacity to deliver senior-focused programs.",
    howToApply: "Apply during open call via ESDC portal.",
  },
  {
    title: "Canada Summer Jobs",
    description: "Non-repayable wage subsidies for non-profits to hire youth aged 15-30 for summer positions. Covers 100% of minimum wage for non-profits.",
    sourceName: "Employment and Social Development Canada (ESDC)",
    sourceUrl: "https://www.canada.ca/en/employment-social-development/services/funding/canada-summer-jobs.html",
    sourceType: "federal",
    category: ["Youth", "Employment"],
    amountMin: 3000, amountMax: 60000,
    deadline: new Date("2027-01-30"),
    eligibility: "Non-profit organizations, public sector employers, and small businesses (under 50 employees). Jobs must be for youth aged 15-30.",
    howToApply: "Apply online through the Canada Summer Jobs portal during the annual intake period (usually late fall).",
  },
  {
    title: "Canada Service Corps — Micro-grants",
    description: "Non-repayable micro-grants to youth (ages 15-30) leading community service projects. Supports volunteer service, leadership, and civic engagement.",
    sourceName: "Canada Service Corps",
    sourceUrl: "https://www.canada.ca/en/services/youth/canada-service-corps/micro-grants.html",
    sourceType: "federal",
    category: ["Youth"],
    amountMin: 250, amountMax: 1500,
    deadline: null,
    eligibility: "Youth leaders aged 15-30 with a community service project idea. Must be Canadian citizen, permanent resident, or protected person.",
    howToApply: "Apply online through the Canada Service Corps portal. Rolling applications.",
  },
  {
    title: "Canada Cultural Investment Fund — Endowment Incentives",
    description: "Matching grants (non-repayable) to arts organizations to build long-term financial stability through endowments.",
    sourceName: "Canadian Heritage",
    sourceUrl: "https://www.canada.ca/en/canadian-heritage/services/funding/cultural-investment-fund.html",
    sourceType: "federal",
    category: ["Culture"],
    amountMin: 10000, amountMax: 2000000,
    deadline: new Date("2026-08-01"),
    eligibility: "Professional not-for-profit arts organizations in Canada. Must meet organizational stability criteria.",
    howToApply: "Submit application during annual intake via Canadian Heritage funding portal.",
  },
  {
    title: "Building Communities Through Arts and Heritage — Local Festivals",
    description: "Non-repayable federal grants for community festivals celebrating local arts and heritage. Covers up to 100% of eligible costs for smaller festivals.",
    sourceName: "Canadian Heritage",
    sourceUrl: "https://www.canada.ca/en/canadian-heritage/services/funding/building-communities/local-festivals.html",
    sourceType: "federal",
    category: ["Culture"],
    amountMin: 1500, amountMax: 200000,
    deadline: new Date("2026-09-15"),
    eligibility: "Non-profit organizations, Indigenous groups, and municipalities organizing local festivals that celebrate arts and heritage.",
    howToApply: "Online application through Canadian Heritage portal. Streamlined for small grants.",
  },
  {
    title: "Building Communities Through Arts and Heritage — Community Anniversaries",
    description: "Non-repayable contribution to fund non-recurring local anniversary celebrations marking milestones of 100+ years.",
    sourceName: "Canadian Heritage",
    sourceUrl: "https://www.canada.ca/en/canadian-heritage/services/funding/building-communities/community-anniversaries.html",
    sourceType: "federal",
    category: ["Culture"],
    amountMin: 1500, amountMax: 200000,
    deadline: new Date("2026-07-15"),
    eligibility: "Non-profits and municipalities planning community anniversary events commemorating 100, 125, 150+ year milestones.",
    howToApply: "Apply online at least 30 weeks before the event.",
  },
  {
    title: "Multiculturalism and Anti-Racism Program — Events Component",
    description: "Non-repayable funding for events promoting intercultural/interfaith understanding and combatting racism and discrimination.",
    sourceName: "Canadian Heritage",
    sourceUrl: "https://www.canada.ca/en/canadian-heritage/services/funding/multiculturalism-anti-racism.html",
    sourceType: "federal",
    category: ["Immigration", "Culture"],
    amountMin: 5000, amountMax: 50000,
    deadline: new Date("2026-11-01"),
    eligibility: "Non-profit organizations, Indigenous groups, educational institutions, and municipalities. Must deliver events that advance anti-racism goals.",
    howToApply: "Submit via online portal at least 12 weeks before event.",
  },
  {
    title: "Settlement Program — Support Services",
    description: "Non-repayable grants for organizations providing settlement services to newcomers to Canada. Covers orientation, language assessment, employment-related services.",
    sourceName: "Immigration, Refugees and Citizenship Canada (IRCC)",
    sourceUrl: "https://www.canada.ca/en/immigration-refugees-citizenship/corporate/partners-service-providers/funding.html",
    sourceType: "federal",
    category: ["Immigration", "Women"],
    amountMin: 100000, amountMax: 5000000,
    deadline: new Date("2026-07-31"),
    eligibility: "Canadian non-profit organizations delivering settlement services outside Quebec (Quebec has separate provincial agreement).",
    howToApply: "Apply during open Calls for Proposals announced by IRCC.",
  },
  {
    title: "Supporting Black Canadian Communities Initiative",
    description: "Non-repayable funding to build capacity of Black-led, Black-serving, and Black-focused community organizations. Covers operations, capital, and capacity building.",
    sourceName: "Employment and Social Development Canada (ESDC)",
    sourceUrl: "https://www.canada.ca/en/employment-social-development/programs/supporting-black-canadian-communities-initiative.html",
    sourceType: "federal",
    category: ["General", "Women", "Youth"],
    amountMin: 25000, amountMax: 1000000,
    deadline: new Date("2026-09-30"),
    eligibility: "Black-led, Black-serving, or Black-focused non-profit organizations and Black-focused projects within organizations.",
    howToApply: "Applications through designated intermediary organizations announced by ESDC.",
  },
  {
    title: "Reaching Home — Designated Communities",
    description: "Non-repayable funding for community efforts to prevent and reduce homelessness. Supports housing-first approach, emergency shelter, and wrap-around services.",
    sourceName: "Infrastructure Canada",
    sourceUrl: "https://www.infrastructure.gc.ca/homelessness-sans-abri/index-eng.html",
    sourceType: "federal",
    category: ["Health", "General"],
    amountMin: 50000, amountMax: 2000000,
    deadline: new Date("2026-10-01"),
    eligibility: "Non-profit organizations, Indigenous organizations, and municipalities in designated communities addressing homelessness.",
    howToApply: "Contact your local Community Advisory Board for the allocation process.",
  },
  {
    title: "Enabling Accessibility Fund — Small Projects",
    description: "Non-repayable grants to improve accessibility of facilities and services for people with disabilities. Covers ramps, accessible washrooms, automatic doors.",
    sourceName: "Employment and Social Development Canada (ESDC)",
    sourceUrl: "https://www.canada.ca/en/employment-social-development/services/funding/enabling-accessibility-fund.html",
    sourceType: "federal",
    category: ["Health", "General"],
    amountMin: 10000, amountMax: 100000,
    deadline: new Date("2026-11-15"),
    eligibility: "Non-profit organizations, small businesses, municipalities, Indigenous organizations. Projects must improve physical accessibility.",
    howToApply: "Apply online during open intake period via ESDC portal.",
  },
  {
    title: "Healthy Canadians and Communities Fund",
    description: "Non-repayable funding for community initiatives promoting healthy living, chronic disease prevention, and mental health support.",
    sourceName: "Public Health Agency of Canada (PHAC)",
    sourceUrl: "https://www.canada.ca/en/public-health/services/funding-opportunities.html",
    sourceType: "federal",
    category: ["Health"],
    amountMin: 100000, amountMax: 5000000,
    deadline: new Date("2026-08-15"),
    eligibility: "Canadian non-profit organizations, Indigenous groups, academic institutions with public health programming.",
    howToApply: "Apply during announced Calls for Applications.",
  },
  {
    title: "Mental Health Promotion Innovation Fund",
    description: "Non-repayable grants for innovative community-based mental health promotion projects for children, youth, and families. Multi-year funding.",
    sourceName: "Public Health Agency of Canada (PHAC)",
    sourceUrl: "https://www.canada.ca/en/public-health/services/funding-opportunities/mental-health-promotion-innovation-fund.html",
    sourceType: "federal",
    category: ["Health", "Youth", "Women"],
    amountMin: 150000, amountMax: 2500000,
    deadline: new Date("2026-12-01"),
    eligibility: "Non-profit organizations with evidence-informed mental health promotion programs. Indigenous-led organizations strongly encouraged.",
    howToApply: "LOI followed by full application process.",
  },
  {
    title: "Racialized Newcomer Women Project",
    description: "Non-repayable funding specifically for projects supporting employment and economic integration of racialized newcomer women.",
    sourceName: "Immigration, Refugees and Citizenship Canada (IRCC)",
    sourceUrl: "https://www.canada.ca/en/immigration-refugees-citizenship/corporate/transparency/program-terms-conditions/settlement.html",
    sourceType: "federal",
    category: ["Women", "Immigration", "Employment"],
    amountMin: 75000, amountMax: 500000,
    deadline: new Date("2026-09-01"),
    eligibility: "Non-profit settlement agencies and women-serving organizations outside Quebec.",
    howToApply: "Apply through IRCC funding calls.",
  },
  {
    title: "Women Entrepreneurship Strategy — Inclusive Strategy",
    description: "Non-repayable contribution for ecosystem partners helping underrepresented women entrepreneurs start and grow businesses.",
    sourceName: "Innovation, Science and Economic Development Canada",
    sourceUrl: "https://ised-isde.canada.ca/site/women-entrepreneurship-strategy/en",
    sourceType: "federal",
    category: ["Women", "Employment"],
    amountMin: 100000, amountMax: 3000000,
    deadline: new Date("2026-10-30"),
    eligibility: "Non-profit organizations with proven track record in supporting women entrepreneurs, especially underrepresented groups.",
    howToApply: "Apply during announced funding calls via ISED portal.",
  },

  // ===== PROVINCIAL (QUEBEC) =====
  {
    title: "Programme Égalité — Projets structurants",
    description: "Subvention non remboursable pour des projets structurants visant l'égalité entre les femmes et les hommes au Québec. Appuie les projets pluriannuels.",
    sourceName: "Secrétariat à la condition féminine du Québec (SCF)",
    sourceUrl: "https://www.quebec.ca/gouvernement/politiques-orientations/plan-action-egalite",
    sourceType: "provincial",
    category: ["Women", "GBV"],
    amountMin: 25000, amountMax: 300000,
    deadline: new Date("2026-09-01"),
    eligibility: "Organismes à but non lucratif québécois dont la mission principale vise l'égalité entre les sexes.",
    howToApply: "Déposer la demande via le portail du SCF. Lettre d'intention puis dossier complet.",
  },
  {
    title: "Programme à l'intention des Autochtones (SCF)",
    description: "Subvention non remboursable destinée aux organismes autochtones qui interviennent auprès des femmes autochtones au Québec.",
    sourceName: "Secrétariat à la condition féminine du Québec (SCF)",
    sourceUrl: "https://scf.gouv.qc.ca",
    sourceType: "provincial",
    category: ["Women", "Immigration"],
    amountMin: 10000, amountMax: 150000,
    deadline: new Date("2026-10-15"),
    eligibility: "Organismes autochtones à but non lucratif offrant des services aux femmes autochtones.",
    howToApply: "Processus de demande via le SCF. Appel annuel.",
  },
  {
    title: "Programme de soutien aux organismes communautaires (PSOC) — Santé",
    description: "Financement de base non remboursable pour la mission globale des organismes communautaires en santé et services sociaux au Québec.",
    sourceName: "Ministère de la Santé et des Services sociaux (MSSS)",
    sourceUrl: "https://www.quebec.ca/sante/systeme-et-services-de-sante/organismes-communautaires",
    sourceType: "provincial",
    category: ["Health", "Women"],
    amountMin: 20000, amountMax: 500000,
    deadline: null,
    eligibility: "Organismes communautaires autonomes reconnus par un CISSS ou CIUSSS avec mission en santé/services sociaux.",
    howToApply: "Contacter le CISSS/CIUSSS de l'Outaouais pour reconnaissance.",
  },
  {
    title: "Fonds d'aide aux victimes d'actes criminels (FAVAC)",
    description: "Subvention non remboursable pour soutenir les organismes aidant les victimes d'actes criminels, incluant les violences conjugales et sexuelles.",
    sourceName: "Ministère de la Justice du Québec",
    sourceUrl: "https://www.justice.gouv.qc.ca/programmes-et-services/aide-aux-victimes-dactes-criminels/",
    sourceType: "provincial",
    category: ["GBV", "Women"],
    amountMin: 15000, amountMax: 250000,
    deadline: new Date("2026-09-30"),
    eligibility: "Organismes à but non lucratif offrant des services directs aux victimes d'actes criminels au Québec.",
    howToApply: "Soumettre une demande via le Ministère de la Justice.",
  },
  {
    title: "Programme de soutien financier en matière d'action bénévole",
    description: "Subvention non remboursable pour des projets qui mettent en valeur et soutiennent l'action bénévole au Québec.",
    sourceName: "Secrétariat à l'action bénévole et communautaire",
    sourceUrl: "https://www.quebec.ca/famille-et-soutien-aux-personnes/aide-et-soutien/benevolat",
    sourceType: "provincial",
    category: ["General"],
    amountMin: 5000, amountMax: 50000,
    deadline: new Date("2026-11-15"),
    eligibility: "Organismes communautaires, centres d'action bénévole, organismes nationaux.",
    howToApply: "Demande annuelle via le portail du Secrétariat.",
  },
  {
    title: "Programme d'aide aux initiatives communautaires (PAIC)",
    description: "Subvention non remboursable pour des projets communautaires favorisant la participation citoyenne et le développement social local.",
    sourceName: "Ministère de la Famille du Québec",
    sourceUrl: "https://www.mfa.gouv.qc.ca",
    sourceType: "provincial",
    category: ["General", "Youth"],
    amountMin: 5000, amountMax: 75000,
    deadline: new Date("2026-10-30"),
    eligibility: "OBNL québécois offrant des services aux familles et à la communauté.",
    howToApply: "Demande via le portail ministériel.",
  },
  {
    title: "Programme d'aide à la citoyenneté et à l'intégration (PACI)",
    description: "Subvention non remboursable pour des projets favorisant l'intégration des personnes immigrantes et la promotion de la diversité.",
    sourceName: "Ministère de l'Immigration, de la Francisation et de l'Intégration (MIFI)",
    sourceUrl: "https://www.quebec.ca/immigration",
    sourceType: "provincial",
    category: ["Immigration", "Women"],
    amountMin: 20000, amountMax: 300000,
    deadline: new Date("2026-09-15"),
    eligibility: "Organismes à but non lucratif offrant des services aux personnes immigrantes au Québec.",
    howToApply: "Déposer via le portail du MIFI pendant l'appel de projets.",
  },
  {
    title: "Programme de soutien en loisirs et sports (PSLS)",
    description: "Subvention non remboursable pour des projets de loisirs, sport, plein air favorisant la participation citoyenne et l'inclusion.",
    sourceName: "Ministère de l'Éducation (MEQ)",
    sourceUrl: "https://www.quebec.ca/education",
    sourceType: "provincial",
    category: ["Youth", "Health"],
    amountMin: 5000, amountMax: 100000,
    deadline: new Date("2026-11-30"),
    eligibility: "Organismes communautaires, scolaires, sportifs et municipalités au Québec.",
    howToApply: "Appel annuel via portail du Ministère.",
  },
  {
    title: "Programme Aide financière aux initiatives culturelles",
    description: "Subvention non remboursable pour des projets culturels favorisant la diversité, la démocratie culturelle et l'accès à la culture.",
    sourceName: "Ministère de la Culture et des Communications du Québec",
    sourceUrl: "https://www.mcc.gouv.qc.ca",
    sourceType: "provincial",
    category: ["Culture"],
    amountMin: 10000, amountMax: 200000,
    deadline: new Date("2026-08-30"),
    eligibility: "Organismes culturels à but non lucratif, artistes, groupes communautaires avec volet culturel.",
    howToApply: "Demande via le portail du MCC pendant les appels de projets.",
  },
  {
    title: "Programme d'action communautaire pour les enfants (PACE)",
    description: "Subvention non remboursable pour des programmes communautaires visant le développement des enfants vulnérables (0-6 ans) et leurs familles.",
    sourceName: "Agence de la santé publique du Canada (entente Québec)",
    sourceUrl: "https://www.canada.ca/fr/sante-publique/services/promotion-sante/enfance-adolescence/programmes-initiatives/programme-action-communautaire-enfants.html",
    sourceType: "provincial",
    category: ["Youth", "Health", "Women"],
    amountMin: 50000, amountMax: 500000,
    deadline: null,
    eligibility: "Organismes communautaires québécois travaillant auprès d'enfants vulnérables et familles à faible revenu.",
    howToApply: "Processus régional par le biais des DSP.",
  },
  {
    title: "Programme de la politique bioalimentaire",
    description: "Subvention non remboursable pour des initiatives locales de sécurité alimentaire, agriculture urbaine et lutte au gaspillage.",
    sourceName: "Ministère de l'Agriculture, des Pêcheries et de l'Alimentation (MAPAQ)",
    sourceUrl: "https://www.mapaq.gouv.qc.ca",
    sourceType: "provincial",
    category: ["Health", "Environment"],
    amountMin: 5000, amountMax: 100000,
    deadline: new Date("2026-10-01"),
    eligibility: "Organismes communautaires, coopératives, municipalités en projet de sécurité alimentaire.",
    howToApply: "Appel de projets via MAPAQ ou partenaires régionaux.",
  },
  {
    title: "Programme de mobilisation-diversité",
    description: "Subvention non remboursable aux organismes locaux pour des projets de rapprochement interculturel et de vivre-ensemble.",
    sourceName: "Ministère de l'Immigration, de la Francisation et de l'Intégration (MIFI)",
    sourceUrl: "https://www.quebec.ca/immigration/participation-collectivite",
    sourceType: "provincial",
    category: ["Immigration", "Culture"],
    amountMin: 10000, amountMax: 75000,
    deadline: new Date("2026-11-01"),
    eligibility: "OBNL, municipalités, MRC qui mènent des projets de rapprochement interculturel.",
    howToApply: "Demande via le portail du MIFI.",
  },
  {
    title: "Programme Soutien à l'autonomie des personnes âgées (SAPA)",
    description: "Subvention non remboursable pour soutenir des organismes offrant du soutien à domicile et de l'accompagnement pour personnes âgées.",
    sourceName: "Ministère de la Santé et des Services sociaux (MSSS)",
    sourceUrl: "https://www.quebec.ca/sante/personnes-agees",
    sourceType: "provincial",
    category: ["Health", "General"],
    amountMin: 20000, amountMax: 200000,
    deadline: null,
    eligibility: "Organismes communautaires offrant des services aux aînés au Québec.",
    howToApply: "Processus régional par l'intermédiaire des CIUSSS.",
  },

  // ===== MUNICIPAL / REGIONAL =====
  {
    title: "Programme de soutien financier aux organismes communautaires — Gatineau",
    description: "Subvention annuelle non remboursable de la Ville de Gatineau pour les organismes communautaires reconnus offrant des services directs aux Gatinoises et Gatinois.",
    sourceName: "Ville de Gatineau",
    sourceUrl: "https://www.gatineau.ca/portail/default.aspx?p=guichet_municipal/subventions",
    sourceType: "municipal",
    category: ["General", "Women", "Youth"],
    amountMin: 2000, amountMax: 50000,
    deadline: new Date("2026-10-15"),
    eligibility: "OBNL enregistrés et opérant à Gatineau depuis minimum un an, reconnus par la Ville.",
    howToApply: "Soumettre via le portail en ligne de la Ville. Période: septembre-octobre annuellement.",
  },
  {
    title: "Soutien aux projets culturels — Ville de Gatineau",
    description: "Subvention non remboursable pour projets artistiques et culturels à Gatineau. Supporte création, diffusion et médiation culturelle.",
    sourceName: "Ville de Gatineau — Service des arts, de la culture et des lettres",
    sourceUrl: "https://www.gatineau.ca/portail/default.aspx?p=culture_patrimoine/soutien_financier",
    sourceType: "municipal",
    category: ["Culture"],
    amountMin: 1000, amountMax: 30000,
    deadline: new Date("2026-09-01"),
    eligibility: "Artistes professionnels, OBNL culturels et collectifs basés à Gatineau.",
    howToApply: "Appel de projets annuel via la Ville de Gatineau.",
  },
  {
    title: "Programme de soutien aux événements — Gatineau",
    description: "Subvention non remboursable pour événements rassembleurs ayant un impact socio-économique et culturel à Gatineau.",
    sourceName: "Ville de Gatineau — Tourisme et événements",
    sourceUrl: "https://www.gatineau.ca/portail/default.aspx?p=tourisme/evenements",
    sourceType: "municipal",
    category: ["Culture", "General"],
    amountMin: 2500, amountMax: 75000,
    deadline: new Date("2026-11-30"),
    eligibility: "OBNL organisateurs d'événements se tenant à Gatineau.",
    howToApply: "Demande en ligne avant la tenue de l'événement.",
  },
  {
    title: "Fonds de développement des territoires (FDT) — MRC des Collines-de-l'Outaouais",
    description: "Subvention non remboursable pour des projets de développement local dans la MRC des Collines-de-l'Outaouais.",
    sourceName: "MRC des Collines-de-l'Outaouais",
    sourceUrl: "https://mrcdescollinesdeloutaouais.qc.ca",
    sourceType: "municipal",
    category: ["General", "Environment"],
    amountMin: 2000, amountMax: 100000,
    deadline: null,
    eligibility: "OBNL, municipalités, coopératives et entreprises d'économie sociale dans la MRC.",
    howToApply: "Demande via la MRC.",
  },
  {
    title: "Fonds régions et ruralité (FRR) — Outaouais",
    description: "Subvention non remboursable pour dynamiser l'économie des territoires ruraux de l'Outaouais.",
    sourceName: "Gouvernement du Québec — MAMH",
    sourceUrl: "https://www.mamh.gouv.qc.ca/developpement-territorial/fonds-regions-et-ruralite",
    sourceType: "provincial",
    category: ["General", "Employment"],
    amountMin: 10000, amountMax: 500000,
    deadline: new Date("2026-12-15"),
    eligibility: "Organismes communautaires et municipaux dans les communautés rurales québécoises.",
    howToApply: "Contacter la MRC ou CLD local pour le processus.",
  },

  // ===== FOUNDATIONS =====
  {
    title: "Canadian Women's Foundation — Economic Development Grants",
    description: "Non-repayable multi-year grants supporting programs that help women out of poverty through economic empowerment, skills training, and entrepreneurship.",
    sourceName: "Canadian Women's Foundation",
    sourceUrl: "https://canadianwomen.org/grants/economic-development/",
    sourceType: "foundation",
    category: ["Women", "Employment"],
    amountMin: 30000, amountMax: 200000,
    deadline: new Date("2026-08-15"),
    eligibility: "Registered charities and qualified donees serving women and gender-diverse people in Canada.",
    howToApply: "Apply through the CWF portal during annual intake period.",
  },
  {
    title: "Canadian Women's Foundation — Violence Prevention Grants",
    description: "Non-repayable grants for community organizations addressing violence against women and gender-based violence. Focuses on prevention and survivor support.",
    sourceName: "Canadian Women's Foundation",
    sourceUrl: "https://canadianwomen.org/grants/violence-prevention/",
    sourceType: "foundation",
    category: ["GBV", "Women"],
    amountMin: 30000, amountMax: 150000,
    deadline: new Date("2026-07-15"),
    eligibility: "Registered charities across Canada delivering GBV prevention and response programs.",
    howToApply: "LOI first, then full proposal for shortlisted applicants.",
  },
  {
    title: "Canadian Women's Foundation — Tween & Teen Girls Program",
    description: "Non-repayable grants for programs empowering girls and gender-diverse youth aged 9-18. Focus on leadership, confidence, and healthy relationships.",
    sourceName: "Canadian Women's Foundation",
    sourceUrl: "https://canadianwomen.org/grants/girls/",
    sourceType: "foundation",
    category: ["Youth", "Women"],
    amountMin: 25000, amountMax: 125000,
    deadline: new Date("2026-09-30"),
    eligibility: "Registered charities operating programs for girls and gender-diverse youth across Canada.",
    howToApply: "Apply through CWF online portal.",
  },
  {
    title: "Centraide Outaouais — Priorités d'investissement communautaire",
    description: "Financement non remboursable pluriannuel pour organismes communautaires de l'Outaouais travaillant en développement social, inclusion, et lutte à la pauvreté.",
    sourceName: "Centraide Outaouais",
    sourceUrl: "https://www.centraide-outaouais.com/financement",
    sourceType: "foundation",
    category: ["General", "Women", "Employment"],
    amountMin: 15000, amountMax: 350000,
    deadline: null,
    eligibility: "OBNL basés en Outaouais avec mission en développement social et lutte à la pauvreté.",
    howToApply: "Processus d'évaluation organisationnelle avec Centraide Outaouais.",
  },
  {
    title: "McConnell Foundation — Community Grants",
    description: "Non-repayable grants for Canadian organizations advancing social innovation and community resilience. Multi-year funding for systemic change.",
    sourceName: "McConnell Foundation",
    sourceUrl: "https://mcconnellfoundation.ca/grants/",
    sourceType: "foundation",
    category: ["General", "Environment"],
    amountMin: 50000, amountMax: 500000,
    deadline: new Date("2026-10-15"),
    eligibility: "Canadian non-profit organizations and qualified donees working on social innovation.",
    howToApply: "Submit LOI through the McConnell Foundation website.",
  },
  {
    title: "Fondation Lucie et André Chagnon — Développement des enfants",
    description: "Subvention non remboursable pluriannuelle pour des projets favorisant le développement des enfants et la prévention de la pauvreté au Québec.",
    sourceName: "Fondation Lucie et André Chagnon",
    sourceUrl: "https://fondationchagnon.org",
    sourceType: "foundation",
    category: ["Youth", "Health", "Women"],
    amountMin: 25000, amountMax: 500000,
    deadline: null,
    eligibility: "OBNL québécois travaillant au développement global des enfants et au soutien des familles.",
    howToApply: "Lettre d'intention via le site Web de la Fondation.",
  },
  {
    title: "Community Foundations of Canada — Investment Readiness Program",
    description: "Non-repayable grants to help social purpose organizations become investment-ready and scale impact.",
    sourceName: "Community Foundations of Canada",
    sourceUrl: "https://communityfoundations.ca/initiatives/investment-readiness-program/",
    sourceType: "foundation",
    category: ["Employment", "General"],
    amountMin: 10000, amountMax: 100000,
    deadline: new Date("2026-09-01"),
    eligibility: "Social purpose organizations including non-profits, charities, and co-operatives.",
    howToApply: "Apply via CFC portal during open intake.",
  },
  {
    title: "Maytree Foundation — Policy Research Grants",
    description: "Non-repayable grants for research and advocacy advancing systemic change on poverty, human rights, and democratic engagement in Canada.",
    sourceName: "Maytree Foundation",
    sourceUrl: "https://maytree.com/what-we-do/grants/",
    sourceType: "foundation",
    category: ["General", "Employment"],
    amountMin: 15000, amountMax: 75000,
    deadline: new Date("2026-08-30"),
    eligibility: "Canadian non-profit organizations engaged in policy research, advocacy, or civic engagement.",
    howToApply: "Contact Maytree for initial conversation, then formal proposal.",
  },
  {
    title: "Laidlaw Foundation — Youth-Led Community Initiative Grants",
    description: "Non-repayable grants supporting youth-led and youth-serving initiatives advancing equity and social change.",
    sourceName: "Laidlaw Foundation",
    sourceUrl: "https://laidlawfdn.org/grants/",
    sourceType: "foundation",
    category: ["Youth"],
    amountMin: 10000, amountMax: 50000,
    deadline: new Date("2026-11-01"),
    eligibility: "Non-profit organizations with youth-led programming. Priority to equity-seeking youth.",
    howToApply: "Open call annually via Laidlaw Foundation website.",
  },
  {
    title: "Lawson Foundation — Children's Outdoor Play",
    description: "Non-repayable grants for initiatives that encourage outdoor play and physical activity among children and youth.",
    sourceName: "Lawson Foundation",
    sourceUrl: "https://lawson.ca/grants/",
    sourceType: "foundation",
    category: ["Youth", "Health"],
    amountMin: 20000, amountMax: 100000,
    deadline: new Date("2026-10-30"),
    eligibility: "Canadian non-profit organizations serving children (ages 2-14) with outdoor play programs.",
    howToApply: "LOI via Lawson Foundation website.",
  },
  {
    title: "Muttart Foundation — Non-profit Sector Capacity Building",
    description: "Non-repayable grants for initiatives strengthening non-profit organizations in Alberta and across Canada.",
    sourceName: "Muttart Foundation",
    sourceUrl: "https://www.muttart.org/funding/",
    sourceType: "foundation",
    category: ["General"],
    amountMin: 10000, amountMax: 75000,
    deadline: new Date("2026-09-15"),
    eligibility: "Canadian registered charities focused on non-profit capacity, early learning, or community development.",
    howToApply: "Apply via Muttart Foundation online portal.",
  },
  {
    title: "Catherine Donnelly Foundation — Social Justice",
    description: "Non-repayable grants for organizations advancing social justice, environmental sustainability, and adult literacy in Canada.",
    sourceName: "Catherine Donnelly Foundation",
    sourceUrl: "https://catherinedonnellyfoundation.ca/grants/",
    sourceType: "foundation",
    category: ["Education", "Environment", "General"],
    amountMin: 10000, amountMax: 100000,
    deadline: new Date("2026-10-01"),
    eligibility: "Canadian non-profit organizations with aligned mission.",
    howToApply: "Submit LOI through CDF website.",
  },
  {
    title: "The Atkinson Foundation — Decent Work",
    description: "Non-repayable grants supporting organizations that promote decent work and economic justice for low-income workers.",
    sourceName: "Atkinson Foundation",
    sourceUrl: "https://atkinsonfoundation.ca/what-we-do/",
    sourceType: "foundation",
    category: ["Employment", "Women"],
    amountMin: 20000, amountMax: 150000,
    deadline: new Date("2026-08-01"),
    eligibility: "Canadian non-profit organizations advancing decent work and economic justice.",
    howToApply: "Contact Foundation for initial conversation, then formal proposal.",
  },
  {
    title: "The J.W. McConnell Family Foundation — Solutions Finance",
    description: "Non-repayable grants and program-related investments for organizations using innovative finance to address social challenges.",
    sourceName: "McConnell Foundation",
    sourceUrl: "https://mcconnellfoundation.ca/solutions-finance/",
    sourceType: "foundation",
    category: ["Employment", "General"],
    amountMin: 50000, amountMax: 500000,
    deadline: new Date("2026-11-30"),
    eligibility: "Organizations piloting or scaling solutions-finance approaches.",
    howToApply: "Email McConnell Foundation program team.",
  },
  {
    title: "Women's Legal Education and Action Fund (LEAF) — Project Grants",
    description: "Non-repayable grants for community projects advancing women's substantive equality through legal literacy and education.",
    sourceName: "LEAF (Women's Legal Education and Action Fund)",
    sourceUrl: "https://www.leaf.ca",
    sourceType: "foundation",
    category: ["Women", "Education"],
    amountMin: 5000, amountMax: 50000,
    deadline: new Date("2026-09-15"),
    eligibility: "Women-serving non-profits running legal literacy, education, or advocacy projects.",
    howToApply: "Apply via LEAF grants portal.",
  },
  {
    title: "The Counselling Foundation of Canada — Career Development",
    description: "Non-repayable grants for programs that support career development and employment for underrepresented groups.",
    sourceName: "Counselling Foundation of Canada",
    sourceUrl: "https://counselling.net/grants/",
    sourceType: "foundation",
    category: ["Employment", "Youth"],
    amountMin: 10000, amountMax: 100000,
    deadline: new Date("2026-10-30"),
    eligibility: "Non-profit organizations delivering career development services.",
    howToApply: "Apply during annual call via Counselling Foundation website.",
  },
  {
    title: "Vancouver Foundation — Pathways & Thriving Communities",
    description: "Non-repayable grants for initiatives that build stronger, more resilient BC communities. Focus on youth, mental health, and equity.",
    sourceName: "Vancouver Foundation",
    sourceUrl: "https://www.vancouverfoundation.ca",
    sourceType: "foundation",
    category: ["Youth", "Health", "General"],
    amountMin: 10000, amountMax: 250000,
    deadline: new Date("2026-09-20"),
    eligibility: "British Columbia-based organizations. Femmeres: check for cross-provincial eligibility.",
    howToApply: "Apply via Vancouver Foundation online portal.",
  },
  {
    title: "Ontario Trillium Foundation — Grow Grants",
    description: "Non-repayable grants to help Ontario non-profits grow their impact and strengthen programs.",
    sourceName: "Ontario Trillium Foundation",
    sourceUrl: "https://otf.ca/our-grants/grow-grants",
    sourceType: "foundation",
    category: ["General", "Youth"],
    amountMin: 50000, amountMax: 250000,
    deadline: new Date("2026-12-01"),
    eligibility: "Ontario-based non-profits with proven track record.",
    howToApply: "Apply through OTF portal during open intake.",
  },

  // ===== PRIVATE / CORPORATE =====
  {
    title: "TD Ready Commitment — Financial Security",
    description: "Non-repayable grants for programs that increase financial security and inclusion for underserved populations.",
    sourceName: "TD Bank Group",
    sourceUrl: "https://www.td.com/ca/en/about-tdc/ready-commitment/financial-security",
    sourceType: "private",
    category: ["Employment", "Women"],
    amountMin: 20000, amountMax: 200000,
    deadline: new Date("2026-07-31"),
    eligibility: "Registered Canadian charities with programs serving equity-deserving groups.",
    howToApply: "Online application during annual intake.",
  },
  {
    title: "TD Ready Commitment — Better Health",
    description: "Non-repayable grants for programs supporting mental health and healthy aging for underserved communities.",
    sourceName: "TD Bank Group",
    sourceUrl: "https://www.td.com/ca/en/about-tdc/ready-commitment/better-health",
    sourceType: "private",
    category: ["Health"],
    amountMin: 20000, amountMax: 200000,
    deadline: new Date("2026-08-15"),
    eligibility: "Registered Canadian charities delivering mental health or healthy aging programs.",
    howToApply: "Apply via TD Ready Commitment portal.",
  },
  {
    title: "RBC Foundation — Emerge Program",
    description: "Non-repayable grants to support youth employment and mental health programs across Canada.",
    sourceName: "RBC Foundation",
    sourceUrl: "https://www.rbc.com/community-social-impact/emerge/",
    sourceType: "private",
    category: ["Youth", "Employment", "Health"],
    amountMin: 10000, amountMax: 150000,
    deadline: new Date("2026-09-30"),
    eligibility: "Registered Canadian charities with youth-focused programming.",
    howToApply: "Apply through RBC Foundation portal.",
  },
  {
    title: "RBC Future Launch",
    description: "Non-repayable grants for programs helping young Canadians (15-29) build skills and successfully transition to employment.",
    sourceName: "RBC Foundation",
    sourceUrl: "https://www.rbc.com/dms/enterprise/futurelaunch/",
    sourceType: "private",
    category: ["Youth", "Employment", "Education"],
    amountMin: 25000, amountMax: 500000,
    deadline: new Date("2026-10-31"),
    eligibility: "Canadian charities serving youth 15-29 with skill-building or employment programs.",
    howToApply: "Apply via RBC Future Launch portal.",
  },
  {
    title: "Bell Let's Talk Community Fund",
    description: "Non-repayable grants supporting community-based mental health programs. Focus on access to care and stigma reduction.",
    sourceName: "Bell Canada",
    sourceUrl: "https://letstalk.bell.ca/en/community-fund",
    sourceType: "private",
    category: ["Health", "Women", "Youth"],
    amountMin: 5000, amountMax: 50000,
    deadline: new Date("2026-07-01"),
    eligibility: "Registered Canadian charities delivering mental health programs.",
    howToApply: "Apply during annual intake period via Bell Let's Talk website.",
  },
  {
    title: "Bell Let's Talk Diversity Fund",
    description: "Non-repayable grants for mental health programs specifically serving BIPOC, 2SLGBTQ+, and underserved communities.",
    sourceName: "Bell Canada",
    sourceUrl: "https://letstalk.bell.ca/en/diversity-fund",
    sourceType: "private",
    category: ["Health", "Women"],
    amountMin: 5000, amountMax: 100000,
    deadline: new Date("2026-09-15"),
    eligibility: "Canadian charities delivering culturally responsive mental health programs.",
    howToApply: "Annual open call through Bell Let's Talk.",
  },
  {
    title: "Desjardins — Fonds du Grand Mouvement",
    description: "Subvention non remboursable pour projets transformateurs dans les communautés desservies par Desjardins. Financement jusqu'à 3 ans.",
    sourceName: "Mouvement Desjardins",
    sourceUrl: "https://www.desjardins.com/fonds-grand-mouvement/",
    sourceType: "private",
    category: ["Employment", "Youth", "Education"],
    amountMin: 25000, amountMax: 500000,
    deadline: new Date("2026-09-30"),
    eligibility: "OBNL dans les communautés Desjardins avec projets à fort impact social.",
    howToApply: "Soumettre une demande via le portail du Fonds du Grand Mouvement.",
  },
  {
    title: "Desjardins — Caisse populaire de Gatineau community fund",
    description: "Local non-repayable grants from the Gatineau Desjardins caisse supporting community initiatives.",
    sourceName: "Desjardins — Caisse populaire de Gatineau",
    sourceUrl: "https://www.desjardins.com/ca/about-us/desjardins/community-involvement/",
    sourceType: "private",
    category: ["General", "Women", "Youth"],
    amountMin: 500, amountMax: 15000,
    deadline: null,
    eligibility: "Non-profits in Gatineau area. Contact local caisse for specific requirements.",
    howToApply: "Contact Caisse populaire de Gatineau directly.",
  },
  {
    title: "Scotiabank ScotiaRISE",
    description: "Non-repayable grants for programs removing barriers to economic resilience for disadvantaged Canadians.",
    sourceName: "Scotiabank",
    sourceUrl: "https://www.scotiabank.com/ca/en/about/scotiarise.html",
    sourceType: "private",
    category: ["Employment", "Women", "Immigration"],
    amountMin: 25000, amountMax: 1000000,
    deadline: new Date("2026-08-01"),
    eligibility: "Registered Canadian charities working on economic resilience for disadvantaged groups.",
    howToApply: "Apply via Scotiabank Community Impact portal.",
  },
  {
    title: "BMO Community Investment Grants",
    description: "Non-repayable grants supporting BMO's focus areas: economic inclusion, environmental sustainability, and advancing Canada's future.",
    sourceName: "BMO Financial Group",
    sourceUrl: "https://corporate.bmo.com/corporate-responsibility/",
    sourceType: "private",
    category: ["Employment", "Environment", "Youth"],
    amountMin: 10000, amountMax: 250000,
    deadline: new Date("2026-11-15"),
    eligibility: "Registered Canadian charities with aligned mission.",
    howToApply: "Submit through BMO community investment portal.",
  },
  {
    title: "CIBC Foundation — Community Support Grants",
    description: "Non-repayable grants for programs in youth empowerment, cancer research support, and community development.",
    sourceName: "CIBC Foundation",
    sourceUrl: "https://www.cibc.com/en/about-cibc/corporate-responsibility.html",
    sourceType: "private",
    category: ["Youth", "Health"],
    amountMin: 10000, amountMax: 150000,
    deadline: new Date("2026-10-15"),
    eligibility: "Registered Canadian charities.",
    howToApply: "Apply via CIBC community investment portal.",
  },
  {
    title: "Google.org Impact Challenge — Canada",
    description: "Non-repayable grants for innovative non-profit ideas using technology to address social challenges.",
    sourceName: "Google.org",
    sourceUrl: "https://www.google.org",
    sourceType: "private",
    category: ["Employment", "Education"],
    amountMin: 100000, amountMax: 1000000,
    deadline: new Date("2026-11-30"),
    eligibility: "Canadian non-profit organizations with innovative tech-enabled solutions.",
    howToApply: "Apply during announced challenges via google.org.",
  },
  {
    title: "Telus Friendly Future Foundation — Youth Health",
    description: "Non-repayable grants for programs supporting health and well-being of Canadian youth, especially from vulnerable groups.",
    sourceName: "Telus Friendly Future Foundation",
    sourceUrl: "https://www.telus.com/en/about/company-overview/community-investment/friendly-future-foundation",
    sourceType: "private",
    category: ["Youth", "Health"],
    amountMin: 5000, amountMax: 50000,
    deadline: new Date("2026-09-30"),
    eligibility: "Registered Canadian charities supporting youth health (under 30).",
    howToApply: "Apply via Telus Friendly Future Foundation website.",
  },
  {
    title: "Canadian Tire Jumpstart — Community Development",
    description: "Non-repayable grants to remove financial barriers to sport and recreation for kids from underserved communities.",
    sourceName: "Canadian Tire Jumpstart Charities",
    sourceUrl: "https://jumpstart.canadiantire.ca/pages/grants",
    sourceType: "private",
    category: ["Youth", "Health"],
    amountMin: 2500, amountMax: 100000,
    deadline: new Date("2026-08-15"),
    eligibility: "Registered Canadian charities providing sport and recreation access for kids.",
    howToApply: "Apply through Jumpstart community development grants portal.",
  },
  {
    title: "Walmart Canada Foundation — Community Grants",
    description: "Non-repayable grants for programs addressing food insecurity, workforce development, and community well-being.",
    sourceName: "Walmart Canada Foundation",
    sourceUrl: "https://www.walmartcanada.ca/community",
    sourceType: "private",
    category: ["Employment", "Health", "General"],
    amountMin: 1000, amountMax: 50000,
    deadline: null,
    eligibility: "Registered Canadian charities with aligned focus areas.",
    howToApply: "Apply via Walmart Canada Foundation portal.",
  },
  {
    title: "Starbucks Foundation — Neighborhood Grants",
    description: "Non-repayable community grants chosen by Starbucks partners for causes important to them locally.",
    sourceName: "Starbucks Foundation",
    sourceUrl: "https://stories.starbucks.com/press/2022/starbucks-foundation-neighborhood-grants/",
    sourceType: "private",
    category: ["General", "Youth"],
    amountMin: 1000, amountMax: 10000,
    deadline: new Date("2026-07-01"),
    eligibility: "Registered Canadian charities nominated by local Starbucks partners.",
    howToApply: "Connect with a local Starbucks partner to nominate your organization.",
  },
  {
    title: "TD Ready Challenge",
    description: "Non-repayable grants (up to $1M) for non-profit solutions to specific annual social issues announced by TD.",
    sourceName: "TD Bank Group",
    sourceUrl: "https://www.td.com/ca/en/about-tdc/ready-commitment/ready-challenge",
    sourceType: "private",
    category: ["Employment", "Health", "Women"],
    amountMin: 100000, amountMax: 1000000,
    deadline: new Date("2026-09-30"),
    eligibility: "Registered Canadian charities with innovative solutions to the annual Challenge theme.",
    howToApply: "Submit innovation proposal during announced Challenge round.",
  },
  {
    title: "Molson Coors — Community Giving",
    description: "Non-repayable grants for community causes including responsible drinking, water stewardship, and community resilience.",
    sourceName: "Molson Coors Canada",
    sourceUrl: "https://www.molsoncoors.com/responsibility/our-community",
    sourceType: "private",
    category: ["General", "Environment"],
    amountMin: 2500, amountMax: 50000,
    deadline: null,
    eligibility: "Registered Canadian charities aligned with Molson Coors priorities.",
    howToApply: "Submit through Molson Coors community giving portal.",
  },
  {
    title: "Loblaw Growing Health Innovations",
    description: "Non-repayable grants for community projects advancing healthy food access and nutrition education.",
    sourceName: "Loblaw Companies Limited",
    sourceUrl: "https://www.loblaw.ca/en/responsibility/people/community.html",
    sourceType: "private",
    category: ["Health", "Youth"],
    amountMin: 5000, amountMax: 100000,
    deadline: new Date("2026-10-15"),
    eligibility: "Canadian non-profit organizations with nutrition or food access programs.",
    howToApply: "Apply via Loblaw community portal during open intake.",
  },
  {
    title: "Home Depot Canada Foundation — Orange Door Project",
    description: "Non-repayable grants for organizations preventing and ending youth homelessness.",
    sourceName: "Home Depot Canada Foundation",
    sourceUrl: "https://homedepot.ca/content/dam/canada/community/orange-door-project.html",
    sourceType: "private",
    category: ["Youth", "General"],
    amountMin: 25000, amountMax: 500000,
    deadline: new Date("2026-11-01"),
    eligibility: "Registered Canadian charities working on youth homelessness.",
    howToApply: "Application process via Home Depot Canada Foundation.",
  },
  {
    title: "Cenovus Energy — Community Investment",
    description: "Non-repayable grants supporting community-based programs in mental health, education, and environment.",
    sourceName: "Cenovus Energy",
    sourceUrl: "https://www.cenovus.com/about/community/community-investment.html",
    sourceType: "private",
    category: ["Health", "Education", "Environment"],
    amountMin: 5000, amountMax: 250000,
    deadline: new Date("2026-09-15"),
    eligibility: "Registered Canadian charities, primarily in Alberta and BC. Check cross-provincial eligibility.",
    howToApply: "Apply via Cenovus community investment portal.",
  },
  {
    title: "Enbridge Fueling Futures Program",
    description: "Non-repayable grants supporting safe communities, environmental stewardship, and community resilience.",
    sourceName: "Enbridge",
    sourceUrl: "https://www.enbridge.com/community-and-indigenous-engagement",
    sourceType: "private",
    category: ["Environment", "General"],
    amountMin: 2500, amountMax: 100000,
    deadline: null,
    eligibility: "Registered Canadian charities in Enbridge operating communities.",
    howToApply: "Apply via Enbridge community investment portal.",
  },
  {
    title: "Coast Capital Savings — Youth Grants",
    description: "Non-repayable grants for programs empowering youth to build brighter futures.",
    sourceName: "Coast Capital Savings",
    sourceUrl: "https://www.coastcapitalsavings.com/we-believe-in-youth",
    sourceType: "private",
    category: ["Youth", "Education"],
    amountMin: 5000, amountMax: 100000,
    deadline: new Date("2026-10-30"),
    eligibility: "Canadian non-profit organizations with youth programming.",
    howToApply: "Apply via Coast Capital portal (BC-based, check eligibility).",
  },
  {
    title: "Air Canada Foundation — Community Grants",
    description: "Non-repayable grants supporting the health and well-being of children.",
    sourceName: "Air Canada Foundation",
    sourceUrl: "https://www.aircanada.com/ca/en/aco/home/about/corporate-sustainability/community.html",
    sourceType: "private",
    category: ["Youth", "Health"],
    amountMin: 1000, amountMax: 50000,
    deadline: new Date("2026-08-15"),
    eligibility: "Registered Canadian charities supporting children's health.",
    howToApply: "Apply through Air Canada Foundation website.",
  },
];

async function main() {
  console.log(`Seeding ${grants.length} real non-refundable grants...`);

  let inserted = 0;
  let skipped = 0;

  for (const g of grants) {
    const urlHash = hash(g.sourceUrl + "::" + g.title);
    try {
      const result = await pool.query(
        `INSERT INTO grants (
          id, title, description, source_name, source_url, source_type,
          category, amount_min, amount_max, deadline, eligibility,
          how_to_apply, is_open, url_hash, scraped_at, updated_at, created_at
        )
        VALUES (gen_random_uuid(), $1, $2, $3, $4, $5::"SourceType", $6, $7, $8, $9, $10, $11, true, $12, NOW(), NOW(), NOW())
        ON CONFLICT (url_hash) DO NOTHING
        RETURNING id`,
        [
          g.title,
          g.description,
          g.sourceName,
          g.sourceUrl,
          g.sourceType,
          g.category,
          g.amountMin,
          g.amountMax,
          g.deadline,
          g.eligibility,
          g.howToApply,
          urlHash,
        ]
      );

      if (result.rowCount && result.rowCount > 0) {
        inserted++;
      } else {
        skipped++;
      }
    } catch (err: any) {
      console.error(`Failed to insert "${g.title}":`, err.message);
    }
  }

  console.log(`Inserted ${inserted} new grants, skipped ${skipped} duplicates.`);

  const countRow = await pool.query("SELECT COUNT(*)::int AS count FROM grants");
  console.log(`Total grants in database: ${countRow.rows[0].count}`);

  await pool.end();
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
